# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles, AutoCorrect.
Lint/EndAlignment:
  Enabled: true

Lint/UselessAssignment:
  Exclude:
    - 'spec/feed_spec.rb'
    - 'spec/integration_spec.rb'

Metrics/AbcSize:
  Max: 22

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 150

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 149

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 24

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Cop supports --auto-correct.
Performance/StringReplacement:
  Enabled: true

Style/AccessorMethodName:
  Exclude:
    - 'lib/stream/client.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
Style/BlockDelimiters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: true

# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: true

# Cop supports --auto-correct.
Style/DefWithParentheses:
  Enabled: true

# Configuration parameters: Exclude.
Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLiteral:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FirstParameterIndentation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues.
Style/HashSyntax:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Cop supports --auto-correct.
Style/IndentArray:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: true

# Cop supports --auto-correct.
Style/MethodCallWithoutArgsParentheses:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodName:
  Enabled: true

# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: true

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
Style/RegexpLiteral:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: MultiSpaceAllowedForOperators.
Style/SpaceAroundOperators:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: true

# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
#Style/TrailingComma:
#  Enabled: true

# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  Enabled: false

# don't complain about code complexity
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
