language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.2.2
  - 2.2.5
  - 2.3.1
  - 2.4.0-preview2

env:
  global:
    - STREAM_REGION=qa

matrix:
  fast_finish: true
  allow_failures:
    - rvm: '2.4.0-preview2'
